apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: build-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: build-controller
    spec:
      containers:
      - name: build-controller
        image: us.gcr.io/convoy-adapter/build-controller:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
